[package]
name = "mksws"
version = "1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
clap = { version = "4.3.0", features = ["derive"] }
rocket = "=0.5.0-rc.3"
